import { IModel } from '../libs';
import { SysExpansionFieldTypeEnum, SysFieldTypeEnum } from '../libs';

export default [
    {
        code: 'sysUser',
        tableName: 'sys_user',
        name: '用户',
        childCodes: ['sysUserFriend'],
        useCreatedFields: true,
        useUpdatedFields: true,
        useLogicDelete: true,
        attributes: {
            username: {
                code: 'username',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'username',
                name: '用户名',
                required: true,
            },
            nickname: {
                code: 'nickname',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'nickname',
                name: '昵称',
                required: true,
            },
            password: {
                code: 'password',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'password',
                name: '密码',
                required: true,
            },
            email: {
                code: 'email',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'email',
                name: '邮箱',
                required: true,
            },
            phone: {
                code: 'phone',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'phone',
                name: '手机号',
                required: true,
            },
            money: {
                code: 'money',
                type: SysExpansionFieldTypeEnum.MONEY,
                columnName: 'money',
                name: '钱',
                required: true,
                default: 0,
            },
            role: {
                code: 'role',
                type: SysFieldTypeEnum.MULTI_QUOTE,
                columnName: 'role',
                name: '角色',
                required: false,
                refCode: 'sysRole',
                refDisplayCode: 'name',
                refFieldCode: 'id',
                midCode: 'sysUserRole',
                selfInMidFieldCode: 'userId',
                refInMidFieldCode: 'roleId',
            },
        },
    },
    {
        code: 'sysRole',
        tableName: 'sys_role',
        name: '角色',
        useCreatedFields: true,
        useUpdatedFields: true,
        useLogicDelete: true,
        attributes: {
            name: {
                code: 'name',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'name',
                name: '名称',
            },
        },
    },
    {
        code: 'sysUserRole',
        tableName: 'sys_user_role',
        name: '用户角色关联表',
        useCreatedFields: true,
        useUpdatedFields: true,
        useLogicDelete: true,
        attributes: {
            userId: {
                code: 'userId',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                columnName: 'user_id',
                name: '用户',
                refCode: 'sysUser',
                refDisplayCode: 'nickname',
                refFieldCode: 'id',
            },
            roleId: {
                code: 'roleId',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                columnName: 'role_id',
                name: '角色',
                refCode: 'sysRole',
                refDisplayCode: 'name',
                refFieldCode: 'id',
            },
        },
    },
    {
        code: 'sysUserFriend',
        tableName: 'sys_user_friend',
        parentCode: 'sysUser',
        parentRefFieldCode: 'userId',
        name: '用户朋友子表',
        useCreatedFields: true,
        useUpdatedFields: true,
        useLogicDelete: true,
        attributes: {
            userId: {
                code: 'userId',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                columnName: 'user_id',
                name: '用户',
                refCode: 'sysUser',
                refDisplayCode: 'nickname',
                refFieldCode: 'id',
            },
            friendId: {
                code: 'friendId',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                columnName: 'friend_id',
                name: '角色',
                refCode: 'sysUser',
                refDisplayCode: 'nickname',
                refFieldCode: 'id',
            },
            isTop: {
                code: 'isTop',
                type: SysFieldTypeEnum.INT,
                columnName: 'is_top',
                name: '是否置顶',
            },
        },
    },

    {
        code: 'equipment',
        tableName: 'equipment',
        name: '设备',
        useCreatedFields: true,
        useUpdatedFields: true,
        useEnabled: true,
        childCodes: ['equipmentFile'],
        attributes: {
            name: {
                code: 'name',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'name',
                name: '名称',
            },
            code: {
                code: 'code',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'code',
                name: '编号',
            },
            // 负责人
            owner: {
                code: 'owner',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                columnName: 'owner',
                name: '负责人',
                refCode: 'sysUser',
                refDisplayCode: 'nickname',
                refFieldCode: 'id',
            },
            // 班组
            team: {
                code: 'team',
                type: SysFieldTypeEnum.MULTI_QUOTE,
                columnName: 'team',
                name: '班组',

                refCode: 'team',
                refDisplayCode: 'name',
                refFieldCode: 'id',
                midCode: 'equipmentTeam',
                selfInMidFieldCode: 'equipmentId',
                refInMidFieldCode: 'teamId',
            },
        },
    },
    {
        code: 'equipmentFile',
        tableName: 'equipment_file',
        parentCode: 'equipment',
        parentRefFieldCode: 'equipmentId',
        name: '设备文件子表',
        useCreatedFields: true,
        useUpdatedFields: true,
        attributes: {
            equipmentId: {
                code: 'equipmentId',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                columnName: 'equipment_id',
                name: '设备',
                refCode: 'equipment',
                refDisplayCode: 'name',
                refFieldCode: 'id',
            },
            name: {
                code: 'name',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'name',
                name: '名称',
            },
            description: {
                code: 'description',
                type: SysFieldTypeEnum.LONG_TEXT,
                columnName: 'description',
                name: '描述',
            },
        },
    },
    {
        code: 'team',
        tableName: 'team',
        name: '班组',
        useCreatedFields: true,
        useUpdatedFields: true,
        attributes: {
            name: {
                code: 'name',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'name',
                name: '名称',
            },
            description: {
                code: 'description',
                type: SysFieldTypeEnum.LONG_TEXT,
                columnName: 'description',
                name: '描述',
            },
        },
    },
    {
        code: 'equipmentTeam',
        tableName: 'equipment_team',
        name: '设备班组关联表',
        attributes: {
            equipmentId: {
                code: 'equipmentId',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                columnName: 'equipment_id',
                name: '设备',
                refCode: 'equipment',
                refDisplayCode: 'name',
                refFieldCode: 'id',
            },
            teamId: {
                code: 'teamId',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                columnName: 'team_id',
                name: '班组',
                refCode: 'team',
                refDisplayCode: 'name',
                refFieldCode: 'id',
            },
        },
    },

    {
        code: 'testAllField',
        tableName: 'test_all_field',
        name: '测试全类型字段',
        attributes: {
            name: {
                code: 'name',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'name',
                name: 'name',
                required: true,
            },
            desc: {
                code: 'desc',
                type: SysExpansionFieldTypeEnum.BIG_TEXT,
                primitiveType: SysFieldTypeEnum.TEXT,
                columnName: 'desc',
                name: 'desc',
                required: true,
            },
            content: {
                code: 'content',
                type: SysFieldTypeEnum.LONG_TEXT,
                columnName: 'content',
                name: 'content',
                required: true,
            },
            like: {
                code: 'like',
                type: SysFieldTypeEnum.INT,
                columnName: 'like',
                name: 'like',
                required: true,
            },
            price: {
                code: 'price',
                type: SysFieldTypeEnum.FLOAT,
                columnName: 'price',
                name: 'price',
                required: true,
            },
            money: {
                code: 'money',
                type: SysExpansionFieldTypeEnum.MONEY,
                primitiveType: SysFieldTypeEnum.FLOAT,
                columnName: 'money',
                name: 'money',
                required: true,
            },
            enabled: {
                code: 'enabled',
                type: SysFieldTypeEnum.SWITCH,
                columnName: 'enabled',
                name: 'enabled',
                required: true,
                default: true,
            },
            labels: {
                code: 'labels',
                type: SysExpansionFieldTypeEnum.MULTI_SELECT,
                primitiveType: SysFieldTypeEnum.JSON,
                columnName: 'labels',
                name: 'labels',
                required: true,
            },
            category: {
                code: 'category',
                type: SysExpansionFieldTypeEnum.SINGLE_SELECT,
                primitiveType: SysFieldTypeEnum.TEXT,
                columnName: 'category',
                name: 'category',
                required: true,
            },
            author: {
                code: 'author',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                columnName: 'author',
                name: 'author',
                required: true,
                refCode: 'sysUser',
                refDisplayCode: 'nickname',
                refFieldCode: 'id',
            },
            color: {
                code: 'color',
                type: SysExpansionFieldTypeEnum.COLOR,
                primitiveType: SysFieldTypeEnum.TEXT,
                columnName: 'color',
                name: 'color',
                required: false,
            },
            meta: {
                code: 'meta',
                type: SysExpansionFieldTypeEnum.JSON_OBJECT,
                columnName: 'meta',
                name: 'meta',
                required: false,
            },
            images: {
                code: 'images',
                type: SysExpansionFieldTypeEnum.JSON_ARRAY,
                columnName: 'images',
                name: 'images',
                required: false,
            },
            uid: {
                code: 'uid',
                type: SysExpansionFieldTypeEnum.UID,
                primitiveType: SysFieldTypeEnum.TEXT,
                columnName: 'uid',
                name: 'uid',
                required: false,
            },
            password: {
                code: 'password',
                type: SysExpansionFieldTypeEnum.ENCRYPT_TEXT,
                primitiveType: SysFieldTypeEnum.TEXT,
                columnName: 'password',
                name: 'password',
                required: false,
            },
        },
    },

    {
        code: 'testUnique',
        name: '测试唯一索引',
        tableName: 'test_unique',
        attributes: {
            name: {
                code: 'name',
                type: SysFieldTypeEnum.TEXT,
                columnName: 'name',
                name: '名称',
                unique: true,
            },
        },
    },
    {
        code: 'learningPlan',
        tableName: 'ls_learning_plans',
        name: '学习计划',
        attributes: {
            name: {
                name: '标题',
                type: SysFieldTypeEnum.TEXT,
                required: true,
                code: 'name',
                columnName: 'name',
            },
            defaultAgentId: {
                name: '默认教学导师',
                type: SysFieldTypeEnum.SINGLE_QUOTE,
                code: 'defaultAgentId',
                columnName: 'default_agent_id',
                refCode: 'agent',
                refDisplayCode: 'name',
                refFieldCode: 'id',
            },
            description: {
                name: '描述',
                type: SysExpansionFieldTypeEnum.BIG_TEXT,
                code: 'description',
                columnName: 'description',
            },
            topic: {
                name: '主题',
                type: SysFieldTypeEnum.LONG_TEXT,
                code: 'topic',
                columnName: 'topic',
            },
            isTop: {
                name: '置顶',
                type: SysFieldTypeEnum.SWITCH,
                code: 'isTop',
                columnName: 'is_top',
                default: false,
            },
            // 'practice_driven', 'theory_practice' 实践驱动 或 理论+实践
            mode: {
                name: '学习模式',
                type: SysExpansionFieldTypeEnum.SINGLE_SELECT,
                code: 'mode',
                columnName: 'mode',
                default: 'practice_driven',
            },
            // 仅章节 或 阶段+章节 'chapters_only', 'stages_and_chapters'
            granularity: {
                name: '颗粒度',
                type: SysExpansionFieldTypeEnum.SINGLE_SELECT,
                code: 'granularity',
                columnName: 'granularity',
                default: 'chapters_only',
            },
            // 生成状态 (技术维度)'pending', 'processing', 'wait-confirm' 'done', 'failed'
            genStatus: {
                name: '生成状态',
                type: SysExpansionFieldTypeEnum.SINGLE_SELECT,
                code: 'genStatus',
                columnName: 'gen_status',
                default: 'pending',
            },
            // 学习进度 (业务维度)'planned', 'processing', 'done', 'archived'
            studyStatus: {
                name: '学习状态',
                type: SysExpansionFieldTypeEnum.SINGLE_SELECT,
                code: 'studyStatus',
                columnName: 'study_status',
                default: 'planned',
            },
            // 在 ls_learning_plans 中增加路径控制策略 guided（引导模式，受依赖限制）；flexible（自由模式，全章节开放）
            pathStrategy: {
                name: '学习策略',
                type: SysExpansionFieldTypeEnum.SINGLE_SELECT,
                code: 'pathStrategy',
                columnName: 'path_strategy',
                default: 'guided',
            },
            createdAt: {
                name: '创建时间',
                type: SysFieldTypeEnum.DATETIME,
                code: 'createdAt',
                columnName: 'created_at',
            },
            updatedAt: {
                name: '更新时间',
                type: SysFieldTypeEnum.DATETIME,
                code: 'updatedAt',
                columnName: 'updated_at',
            },
        },
    },
    {
        code: 'agent',
        tableName: 'lli_agent',
        name: 'Agent',
        attributes: {
            name: {
                name: '名称',
                type: SysFieldTypeEnum.TEXT,
                required: true,
                unique: true,
                code: 'name',
                columnName: 'name',
            },
            // worker, ceo, supervisor
            type: {
                name: '类型',
                type: SysExpansionFieldTypeEnum.SINGLE_SELECT,
                required: true,
                unique: true,
                code: 'type',
                columnName: 'type',
                default: 'worker',
            },
            capabilities: {
                name: '能力',
                type: SysExpansionFieldTypeEnum.JSON_ARRAY,
                code: 'capabilities',
                columnName: 'capabilities',
            },
            availableTools: {
                // （空数组=允许全部工具）
                name: '工具白名单',
                type: SysExpansionFieldTypeEnum.JSON_ARRAY,
                code: 'availableTools',
                columnName: 'available_tools',
            },
            promptTemplate: {
                name: '提示词',
                type: SysFieldTypeEnum.LONG_TEXT,
                required: true,
                code: 'promptTemplate',
                columnName: 'prompt_template',
            },
            maxToolRounds: {
                name: '工具最大调用次数',
                type: SysFieldTypeEnum.INT,
                default: 5,
                code: 'maxToolRounds',
                columnName: 'max_tool_rounds',
                precise: 0,
            },
            kbScope: {
                name: '知识库搜索范围',
                type: SysExpansionFieldTypeEnum.SINGLE_SELECT,
                default: 'system',
                enum: 'kbScope',
                code: 'kbScope',
                columnName: 'kb_scope',
            },
            enabled: {
                name: '默认',
                type: SysFieldTypeEnum.SWITCH,
                default: true,
                code: 'enabled',
                columnName: 'enabled',
            },
            createdAt: {
                name: '创建时间',
                type: SysFieldTypeEnum.DATETIME,
                code: 'createdAt',
                columnName: 'created_at',
            },
        },
    },
] as IModel[];
